# Generated by Django 4.2.7 on 2023-12-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('not_selected', 'NOT_SELECTED')], default='not_selected', max_length=25)),
            ],
        ),
    ]
