# Generated by Django 4.2.7 on 2023-12-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp', '0002_user2'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25)),
                ('phone', models.IntegerField()),
                ('gmail', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('Not_specified', 'NOT_SPECIFIED')], default='Not_specified', max_length=20)),
            ],
        ),
    ]
