# Generated by Django 4.2.7 on 2023-12-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp', '0003_user_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
