# Generated by Django 4.2.7 on 2024-01-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp', '0005_doctor_form1'),
    ]

    operations = [
        migrations.CreateModel(
            name='appoint_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('data', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=25)),
                ('department', models.CharField(max_length=25)),
                ('message', models.CharField(max_length=2000)),
                ('payment_id', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('Not_specified', 'NOT_SPECIFIED')], default='Not_specified', max_length=20)),
                ('status', models.CharField(choices=[('approve', 'approve'), ('reject', 'reject'), ('pending', 'pending')], default='pending', max_length=10)),
            ],
        ),
    ]
