# Generated by Django 4.2.7 on 2024-01-03 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosp', '0006_appoint_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appoint_booking',
            old_name='data',
            new_name='date',
        ),
    ]
